---
services:
  shopizer-db:
    environment:
      - MYSQL_ROOT_PASSWORD=shopizer123
      - MYSQL_DATABASE=SALESMANAGER
      - MYSQL_USER=shopizer_db_user
      - MYSQL_PASSWORD=shopizer_db_password
    image: mysql/mysql-server:5.7
    container_name: shopizer-db
    networks:
      - shopizer-network
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
  shopizer:
    depends_on:
      - shopizer-db
    environment:
      - "SPRING_PROFILES_ACTIVE=cloud"
      - "JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "elasticsearch.server.host=http://shopizer-es"
      - "elasticsearch.server.port=9200"
      - "db.jdbcUrl=jdbc:mysql://shopizer-db:3306/SALESMANAGER?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8"
      - "db.user=shopizer_db_user"
      - "db.password=shopizer_db_password"
      - "config.cms.method=gcp"
      - "config.cms.contentUrl=https://console.cloud.google.com/storage/browser/shopizer-demo"
      - "GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/shopizer-storage.json"
      - "AWS_ACCESS_KEY_ID=NO"
      - "AWS_SECRET_ACCESS_KEY=NO"
      - "config.cms.gcp.bucket=shopizer-demo"
      - "config.cms.aws.bucket=NO"
      - "config.cms.aws.region=NO"
      - "elasticsearch.security.password=NOTREQUIRED"
      - "config.displayShipping=true"
      - "config.googleMapsKey=GOOGLE-MAPS-API-KEY"
      - "config.recaptcha.secretKey=RECAPTCHA-SECRET-KEY"
      - "config.recaptcha.siteKey=RECAPTCHA-SITE-KEY"
    image: shopizerecomm/shopizer:master-1573694054
    image: gcr.io/plexiform-timer-209901/shopizer
    container_name: shopizer
    mem_limit: 1024m
    networks:
      - shopizer-network
    links:
      - shopizer-db
    ports:
      - "8080:8080"
  shopizer-es:
    environment:
      - "cluster.name=shopizer"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.1
    container_name: shopizer-es
    networks:
      - shopizer-network
    mem_limit: 1g
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
#      - ./es:/usr/share/elasticsearch/data
      - /usr/share/elasticsearch/data
version: "2.2"

networks:
  shopizer-network:
