version: '3'
services:
  # Local storage
  nginx: 
    image: nginx:latest
    container_name: nginx
    networks:
      - shopizer-network
    ports: 
      - "80:80"
    volumes: 
      - ./images:/usr/share/nginx/html
  shopizer-db: 
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd001!
      - MYSQL_DATABASE=SALESMANAGER
      - MYSQL_USER=shopizer_db_user
      - MYSQL_PASSWORD=shopizer_db_password
    image: mysql:8.0.28
    container_name: shopizer-db
    networks:
      - shopizer-network
    ports: 
      - "3307:3306"
    volumes: 
      - ./db:/var/lib/mysql
  #shopizer: 
  #  depends_on: 
  #    - shopizer-db
  #  environment: 
  #    - "SPRING_PROFILES_ACTIVE=cloud"
  #    - "JAVA_OPTS=-Xms1024m -Xmx1024m"
  #    # ----------------
  #    # OpenSearch
  #    # ---------------
  #    - "search.credentials.username=admin"
  #    - "search.credentials.password=admin"
  #    - "search.clusterName=opensearch-cluster"
  #    - "search.searchLanguages=en"
  #    - "search.host[0].scheme=http"
  #    - "search.host[0].host=opensearch-node1"
  #    - "search.host[0].port=9200"
  #    - "search.host[1].scheme=http"
  #    - "search.host[1].host=opensearch-node2"
  #    - "search.host[1].port=9201"
  #    # ----------------
  #    # Database
  #    # ---------------
  #    - "db.jdbcUrl=jdbc:mysql://shopizer-db:3306/SALESMANAGER?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8"
  #    - "db.user=shopizer_db_user"
  #    - "db.password=shopizer_db_password"
  #    # ----------------
  #    # Image storage
  #    # ---------------
  #    - "config.cms.method=aws"
  #    - "config.cms.contentUrl=https://s3.ca-central-1.amazonaws.com/shopizer"
  #    - "AWS_ACCESS_KEY_ID=<YOUR ACCESS KEY>"
  #    - "AWS_SECRET_ACCESS_KEY=<YOUR SECRET ACCESS_KEY>"
  #    - "config.cms.aws.bucket=shopizer"
  #    - "config.cms.aws.region=ca-central-1"
  #    # ----------------
  #    # Runtime config
  #    # ---------------
  #    - "config.displayShipping=true"
  #    - "config.shippingDistancePreProcessor.acceptedZones=QC,ON,NB,NY,CA,FL,NC,SC"
  #    - "config.shippingDistancePreProcessor.apiKey=YOUR-GOOGLE-PLACES-KEY"
  #    # ----------------
  #    # Out mail (requires AWS SES)
  #    # ---------------
  #    - "config.emailSender=ses"
  #    - "config.emailSender.region=US_EAST_1"
  #  image: shopizerecomm/shopizer:3.2.5
  #  pull_policy: always
  #  container_name: shopizer
  #  mem_limit: 2048m
  #  networks:
  #    - shopizer-network
  #  links: 
  #    - shopizer-db
  #  ports: 
  #    - "8080:8080"
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - shopizer-network
  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    ports:
      - 9201:9200
      - 9601:9600 # required for Performance Analyzer
    networks:
      - shopizer-network
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200","http://opensearch-node2:9200"]'
    networks:
      - shopizer-network

volumes:
  opensearch-data1:
  opensearch-data2:


networks:
  shopizer-network:
